Repository gsjuradog/trademon, pull requests merged in 2021-02, with the labels that each got.

#33 Created Hamburger Menu, DM Summary, New Routes, Styling Updates
  client/trademon/public/assets/exit-icon-hover.png
  client/trademon/public/assets/exit-icon.png
  client/trademon/public/assets/trademon-logo.png
  client/trademon/src/App.tsx
  client/trademon/src/components/aaPageComponents/dmPage.tsx
  client/trademon/src/components/formComponents/createListingForm.tsx
  client/trademon/src/components/formComponents/placeholder.tsx
  client/trademon/src/components/navComponents/searchComponents/profileOverlayComponent.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmSummaryTile.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/profileOverlayComponent.tsx
  client/trademon/src/styling/navs.scss
  client/trademon/src/styling/tiles.scss
Labels: enhancement, feature, front-end

#37 Feat Implemented Offer Form
  client/trademon/src/components/formComponents/createListingForm.tsx
  client/trademon/src/styling/forms.scss
  client/trademon/src/styling/navs.scss
Labels: feature, front-end

#40 BackEnd-Feat/Populated poke trade table and routes
  server/controllers/tradeController.js
  server/dumbyData/pokedata.json
  server/index.js
  server/models/poketrade.model.js
  server/models/tradeData.model.js
  server/routes.js
Labels: back-end, feature

#43 BackendFeat/Implemented sign up route using bcrypt, store to usercreds & userData tables
  server/controllers/authController.js
  server/controllers/userController.js
  server/models/userCredentials.model.js
  server/models/userData.model.js
  server/models/userTokens.model.js
  server/routes.js
  server/services/services.js
Labels: back-end, feature

#45 Backend-Feat/Created Sign In Functionality With Tokens & Bcrypt Compare
  server/controllers/authController.js
  server/models/userTokens.model.js
  server/routes.js
Labels: back-end, feature

#48 Closed Fetch data to edit tiles/
  client/trademon/.eslintcache
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/tileComponents/standardTileComponent.tsx
  client/trademon/src/utils/rest.ts
Labels: feature, front-end

#51 Backend-Ft/HEROKU DEPLOYMENT
  Procfile
  client/trademon/public/assets/Logo-Update-Glow-Tranparent.png
  package-lock.json
  package.json
  server/.envCopy
  server/index.js
  server/models/index.js
Labels: back-end, feature

#63 Frontend Fix/Fix 250% Zoom, Convert Pixels to VH, VW, and VW calcs
  client/trademon/src/App.scss
  client/trademon/src/components/aaPageComponents/dmChatPage.tsx
  client/trademon/src/components/aaPageComponents/dmPage.tsx
  client/trademon/src/components/aaPageComponents/offerDetailsPage.tsx
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/navComponents/searchComponents/profileOverlayComponent.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/tileComponents/miniTileComponent.tsx
  client/trademon/src/components/tileComponents/standardTileComponent.tsx
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/modal.scss
  client/trademon/src/styling/navs.scss
  client/trademon/src/styling/rating.scss
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/rest.ts
  server/controllers/pokeStaticController.js
  server/models/pokeStatic.model.js
  server/routes.js
Labels: feature, front-end

#56 Backend-Feat/Added Static Data Table W/ Cloudinary Links & Route
  server/controllers/pokeStaticController.js
  server/models/pokeStatic.model.js
  server/routes.js
Labels: back-end, feature

#71 feat(put and delete trades): pUT AND DELETE TRADES
  client/trademon/public/index.html
  client/trademon/public/manifest.json
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/utils/rest.ts
  server/controllers/tradeController.js
  server/routes.js
Labels: back-end, feature

#72 Frontend feat state
  client/trademon/package-lock.json
  client/trademon/package.json
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/testComponents/reduxTestComponent.tsx
  client/trademon/src/components/testComponents/reduxTestListComponent.tsx
  client/trademon/src/index.tsx
  client/trademon/src/redux/reducers/pokemonsSlice.tsx
  client/trademon/src/redux/store.ts
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/searchSlice.ts
  client/trademon/src/store/store.ts
Labels: feature, front-end

#77 Backendfix/change fetch static to get
  server/models/index.js
  server/routes.js
Labels: back-end

#82 Frontend-Feat/upgradedMyProfile,Scss,DynamicTradeUrlRoutes
  client/trademon/src/App.scss
  client/trademon/src/App.tsx
  client/trademon/src/components/formComponents/createListingForm.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/profileBannerComponent.tsx
  client/trademon/src/components/tileComponents/standardTileComponent.tsx
  client/trademon/src/styling/forms.scss
  client/trademon/src/styling/myProf.scss
  client/trademon/src/styling/navs.scss
  client/trademon/src/styling/rating.scss
  client/trademon/src/utils/interfaces.ts
Labels: feature, front-end

#88 Front end feat/Form Submits Valid Object Into Table & Redirects User
  client/trademon/src/components/formComponents/createListingForm.tsx
  client/trademon/src/utils/rest.ts
  server/controllers/tradeController.js
  server/models/index.js
  server/models/pokeStatic.model.js
  server/routes.js
Labels: feature, front-end

#90 FE & BE Fixes & Feats
  client/trademon/src/components/aaPageComponents/offerDetailsPage.tsx
  client/trademon/src/utils/rest.ts
  server/controllers/mtgoTradeController.js
  server/models/mtgoTrade.model.js
Labels: back-end, bug, feature, front-end

#94 Frontend feat/offer details page
  client/trademon/src/components/tileComponents/miniTileComponent.tsx
  client/trademon/src/styling/containers.scss
  server/controllers/authController.js
  server/models/index.js
Labels: bug

#97 feat(be_mtgo controller, route): route and controller to find one MTG…
  server/controllers/mtgoTradeController.js
  server/routes.js
Labels: back-end

#99 Backend feat graphql resolvers
  client/trademon/src/App.scss
  client/trademon/src/App.tsx
  client/trademon/src/components/aaPageComponents/dmChatPage.tsx
  client/trademon/src/components/aaPageComponents/loginPage.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/testComponent/testComponent.tsx
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/login.scss
  client/trademon/src/styling/navs.scss
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/animations.ts
  client/trademon/src/utils/graphql.ts
  client/trademon/src/utils/rest.ts
  server/controllers/messageController.js
  server/controllers/resolvers.js
  server/index.js
  server/models/message.model.js
  server/package.json
  server/schema.graphql
Labels: back-end, feature, front-end

#100 Frontend fix/disable table assc
  server/models/index.js
  server/models/userCredentials.model.js
  server/models/userData.model.js
  server/routes.js
Labels: back-end, bug

#101 fix(fixed mgto backendroutes): fixed MGTO BackendRoutes
  client/trademon/src/utils/rest.ts
  server/controllers/mtgoTradeController.js
  server/models/index.js
  server/models/mtgoTrade.model.js
Labels: bug

#114 Frontend fix/fix all front end comps to new be
  client/trademon/src/components/aaPageComponents/loginPage.tsx
  client/trademon/src/components/containerComponents/platformContainer.tsx
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/tileComponents/MTGstandardTileComponent.tsx
  client/trademon/src/components/tileComponents/miniTileComponent.tsx
  client/trademon/src/components/tileComponents/standardTileComponent.tsx
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/miniTileSlice.ts
  client/trademon/src/store/standardTileSlice.ts
  client/trademon/src/utils/rest.ts
  server/index.js
  server/models/index.js
Labels: bug, front-end

#118 Fe feat/account state implementation
  client/trademon/src/components/aaPageComponents/loginPage.tsx
  client/trademon/src/store/authSlice.ts
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/miniTileSlice.ts
  client/trademon/src/store/store.ts
  client/trademon/src/store/userSlice.ts
  client/trademon/src/utils/rest.ts
  server/controllers/chatController.js
  server/controllers/messageController.js
  server/controllers/mtgoTradeController.js
  server/models/userData.model.js
  server/routes.js
Labels: feature, front-end

#122 Frontend feat store/world
  client/trademon/package-lock.json
  client/trademon/package.json
  client/trademon/src/components/aaPageComponents/MagicTheGatheringPage.tsx
  client/trademon/src/components/aaPageComponents/landingPage.tsx
  client/trademon/src/components/aaPageComponents/pokemonGoPage.tsx
  client/trademon/src/components/containerComponents/platformContainer.tsx
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/tileComponents/miniTileComponent.tsx
  client/trademon/src/store/EpicSearchSlice.ts
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/standardTileSlice.ts
  client/trademon/src/store/store.ts
  client/trademon/src/store/worldSlice.ts
Labels: feature, front-end, refactor

#126 FIX POKE FORM CREATION WITH NEW BACKEND
  client/trademon/src/components/formComponents/createListingForm.tsx
  client/trademon/src/utils/rest.ts
Labels: bug, front-end

#128 feat: refactor GraphQL after DB change
  client/trademon/src/App.tsx
  client/trademon/src/components/testComponent/testComponent.tsx
  client/trademon/src/utils/graphql.ts
  server/controllers/resolvers.js
  server/schema.graphql
Labels: back-end, refactor

#127 Frontend-Feat/Standard Tiles Update
  client/trademon/src/App.tsx
  client/trademon/src/components/aaPageComponents/offerDetailsPageMTGO.tsx
  client/trademon/src/components/aaPageComponents/offerDetailsPagePokemon.tsx
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/tileComponents/standardTileMTGO.tsx
  client/trademon/src/components/tileComponents/standardTilePokemon.tsx
  client/trademon/src/styling/tiles.scss
  server/models/pokeTradeData.model.js
Labels: feature, front-end

#129 Frontend feat/Poke Components Improvements
  client/trademon/public/assets/Shiny Badge2.png
  client/trademon/public/assets/ShinyBadge.png
  client/trademon/public/assets/bg_MTGO.jpg
  client/trademon/public/assets/bg_Pokemon GO.jpg
  client/trademon/src/App.scss
  client/trademon/src/App.tsx
  client/trademon/src/assets/bg_trade_MTGO.jpg
  client/trademon/src/components/aaPageComponents/landingPage.tsx
  client/trademon/src/components/aaPageComponents/offerDetailsPagePokemon.tsx
  client/trademon/src/components/containerComponents/platformContainer.tsx
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/tileComponents/miniTileComponent.tsx
  client/trademon/src/components/tileComponents/standardTilePokemon.tsx
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/miniTileSlice.ts
  client/trademon/src/store/standardTileSlice.ts
  client/trademon/src/styling/_config.scss
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/graphql.ts
  client/trademon/src/utils/helperFunction.ts
  client/trademon/src/utils/interfaces.ts
  client/trademon/src/utils/rest.ts
  server/models/index.js
Labels: feature, front-end

#131 fix/ReducedChromeWarnings PokeBadeSystemImprovements
  client/trademon/src/components/aaPageComponents/WorldOfWarcraftPage.tsx
  client/trademon/src/components/aaPageComponents/contactSeller.tsx
  client/trademon/src/components/aaPageComponents/demoAnimation.tsx
  client/trademon/src/components/aaPageComponents/loginPage.tsx
  client/trademon/src/components/aaPageComponents/offerDetailsPagePokemon.tsx
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/aaPageComponents/trade_dmPage.tsx
  client/trademon/src/components/containerComponents/platformContainer.tsx
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/modal/drawer.tsx
  client/trademon/src/components/navComponents/searchComponents/profileOverlayComponent.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmSummaryTile.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/profileBannerComponent.tsx
  client/trademon/src/components/tileComponents/standardTilePokemon.tsx
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/miniTileSlice.ts
  client/trademon/src/store/standardTileSlice.ts
  client/trademon/src/store/userSlice.ts
  client/trademon/src/store/worldSlice.ts
  client/trademon/src/styling/myProf.scss
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/helperFunction.ts
  client/trademon/src/utils/rest.ts
Labels: bug, front-end

#134 feat/MyProfile Values Populating Dynamically & State Improvements
  client/trademon/src/App.tsx
  client/trademon/src/components/aaPageComponents/loginPage.tsx
  client/trademon/src/components/containerComponents/platformContainer.tsx
  client/trademon/src/components/modal/backdrop.jsx
  client/trademon/src/components/modal/drawer.tsx
  client/trademon/src/components/navComponents/searchComponents/profileOverlayComponent.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/profileBannerComponent.tsx
  client/trademon/src/store/miniTileSlice.ts
  client/trademon/src/store/standardTileSlice.ts
  client/trademon/src/store/userSlice.ts
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/modal.scss
  client/trademon/src/styling/navs.scss
Labels: feature, front-end

#135 Fe-Feat/PokeTradeDetails Page Updates & Trade page update
  client/trademon/src/App.scss
  client/trademon/src/assets/users/user1.png
  client/trademon/src/assets/users/user2.png
  client/trademon/src/components/aaPageComponents/landingPage.tsx
  client/trademon/src/components/aaPageComponents/offerDetailsPagePokemon.tsx
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/aaPageComponents/trade_dmPage.tsx
  client/trademon/src/components/testComponent/testComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/profileBannerComponent.tsx
  client/trademon/src/components/tileComponents/standardTilePokemon.tsx
  client/trademon/src/styling/_config.scss
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/temp_tradePage.scss
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/helperFunctions.ts
  client/trademon/src/utils/interfaces.ts
  client/trademon/src/utils/rest.ts
  server/controllers/authController.js
  server/controllers/pokeTradeController.js
  server/models/userData.model.js
  server/routes.js
Labels: feature, front-end

#144 fix(backend): fixed Create pokeTrade controller
  server/controllers/mtgoTradeController.js
  server/controllers/pokeTradeController.js
  server/models/index.js
  server/models/userData.model.js
Labels: back-end

#142 Fe/rest create mtgo trade function
  client/trademon/src/components/aaPageComponents/offerDetailsPageMTGO.tsx
  client/trademon/src/utils/interfaces.ts
  client/trademon/src/utils/rest.ts
Labels: feature, front-end

#147 Feat/Socketio & Tradepage
  client/trademon/package-lock.json
  client/trademon/package.json
  client/trademon/src/components/aaPageComponents/dmChatPage.tsx
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/aaPageComponents/trade_dmPage.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmChatTile.tsx
  client/trademon/src/styling/temp_tradePage.scss
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/interfaces.ts
  package-lock.json
  package.json
  server/index.js
  server/package-lock.json
  server/package.json
Labels: back-end, feature, front-end

#149 refactor(routing): routes change from link to useHistory
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/navComponents/searchComponents/profileOverlayComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmSummaryTile.tsx
  client/trademon/src/components/tileComponents/standardTileMTGO.tsx
Labels: front-end, refactor

#152 Mtgo tiles view fixed, added column seller to models
  client/trademon/src/components/aaPageComponents/offerDetailsPageMTGO.tsx
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/tileComponents/miniTileComponent.tsx
  client/trademon/src/store/interfaces.ts
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/helperFunctions.ts
  client/trademon/src/utils/interfaces.ts
  server/controllers/mtgoTradeController.js
  server/models/mtgoTrade.model.js
Labels: back-end, front-end, refactor

#153 Frontend feat search
  client/trademon/src/App.tsx
  client/trademon/src/components/aaPageComponents/landingPage.tsx
  client/trademon/src/components/aaPageComponents/loginPage.tsx
  client/trademon/src/components/aaPageComponents/offerDetailsPageMTGO.tsx
  client/trademon/src/components/containerComponents/platformContainer.tsx
  client/trademon/src/components/navComponents/searchComponents/profileOverlayComponent.tsx
  client/trademon/src/components/tileComponents/miniTileComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmChatTile.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/myOffersComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/profileBannerComponent.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/watchListComponent.tsx
  client/trademon/src/components/tileComponents/standardTileMTGO.tsx
  client/trademon/src/components/tileComponents/standardTilePokemon.tsx
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/miniTileSlice.ts
  client/trademon/src/store/userSlice.ts
  client/trademon/src/utils/helperFunctions.ts
  client/trademon/src/utils/interfaces.ts
  client/trademon/src/utils/rest.ts
  server/controllers/authController.js
Labels: bug, enhancement, front-end, refactor

#154 fix(standardmtgotile class names): changed styles and fixed hover
  client/trademon/src/components/tileComponents/standardTileMTGO.tsx
  client/trademon/src/styling/tiles.scss
Labels: front-end

#155 Fe-Feat/Trade Room Update & Connected Routes
  client/trademon/public/assets/notificationIcon.png
  client/trademon/src/App.tsx
  client/trademon/src/components/aaPageComponents/contactSeller.tsx
  client/trademon/src/components/aaPageComponents/dmPage.tsx
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmSummaryTile.tsx
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/interfaces.ts
Labels: feature, front-end

#156 refactor(platform-container): add background to rocket league
  client/trademon/public/assets/bg_RocketLeague.jpg
  client/trademon/src/components/aaPageComponents/landingPage.tsx
  client/trademon/src/components/aaPageComponents/pokemonGoPage.tsx
  client/trademon/src/components/containerComponents/platformContainer.tsx
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/miniTileSlice.ts
  client/trademon/src/store/standardTileSlice.ts
Labels: front-end, refactor

#159 fix(fe wow and rl tiles): populate wow and rocket
  client/trademon/public/assets/RL/r1.png
  client/trademon/public/assets/RL/r2.png
  client/trademon/public/assets/RL/r3.png
  client/trademon/public/assets/RL/r4.png
  client/trademon/public/assets/RL/r5.png
  client/trademon/public/assets/RL/r6.png
  client/trademon/public/assets/WoW/1.png
  client/trademon/public/assets/WoW/2.png
  client/trademon/public/assets/WoW/3.png
  client/trademon/public/assets/WoW/4.png
  client/trademon/public/assets/WoW/5.png
  client/trademon/src/components/containerComponents/platformContainer.tsx
Labels: front-end

#161 feat: add rating to feedback form
  client/trademon/src/components/aaPageComponents/demoAnimation.tsx
  client/trademon/src/components/formComponents/feedbackForm.tsx
  client/trademon/src/styling/forms.scss
  client/trademon/src/utils/animations.ts
Labels: feature, front-end

#160 feat(fe profile page): populated watchlist
  client/trademon/src/components/aaPageComponents/myProfilePage.tsx
  client/trademon/src/components/containerComponents/platformContainer.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/watchListComponent.tsx
  client/trademon/src/components/tileComponents/standardTilePokemon.tsx
Labels: feature, front-end

#163 feat: completed Feedback Form
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/formComponents/feedbackForm.tsx
  client/trademon/src/styling/forms.scss
  client/trademon/src/utils/animations.ts
Labels: feature, front-end

#164 Frontend feat search
  client/trademon/public/assets/bernie.png
  client/trademon/public/assets/wow/1.png
  client/trademon/public/assets/wow/2.png
  client/trademon/public/assets/wow/3.png
  client/trademon/public/assets/wow/4.png
  client/trademon/public/assets/wow/5.png
  client/trademon/src/assets/bernie.png
  client/trademon/src/components/aaPageComponents/offerDetailsPagePokemon.tsx
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/containerComponents/searchResultsContainer.tsx
  client/trademon/src/components/navComponents/searchComponents/searchBarComponent.tsx
  client/trademon/src/components/tileComponents/standardTilePokemon.tsx
  client/trademon/src/store/EpicSearchSlice.ts
  client/trademon/src/store/interfaces.ts
  client/trademon/src/store/searchSlice.ts
  client/trademon/src/store/standardTileSlice.ts
  client/trademon/src/store/store.ts
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/navs.scss
  client/trademon/src/styling/temp_tradePage.scss
  client/trademon/src/styling/tiles.scss
Labels: bug, enhancement, front-end

#165 feat: demo animation update
  client/trademon/public/assets/lightning-trim.mp4
  client/trademon/src/components/aaPageComponents/demoAnimation.tsx
  client/trademon/src/styling/demo.scss
  client/trademon/src/utils/animations.ts
Labels: feature, front-end

#166 fix(fe css fixes): fE Css fixes
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/myProf.scss
  client/trademon/src/styling/tiles.scss
Labels: bug, front-end

#167 feat: minor CSS fixes on offer page cards
  client/trademon/src/components/aaPageComponents/contactSeller.tsx
  client/trademon/src/styling/containers.scss
Labels: enhancement, front-end

#183 feat(searchcomponent): add search bar to pokemon page
  client/trademon/src/components/aaPageComponents/pokemonGoPage.tsx
  client/trademon/src/components/navComponents/searchComponents/searchComponent.tsx
Labels: feature, front-end

#184 Fe/be chat fixes rest functions and chat tab funcionality
  client/trademon/src/components/aaPageComponents/contactSeller.tsx
  client/trademon/src/components/aaPageComponents/offerDetailsPageMTGO.tsx
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/containerComponents/chatContainer.tsx
  client/trademon/src/components/containerComponents/offerDetailsPokemon.tsx
  client/trademon/src/components/navComponents/tabsComponent.tsx
  client/trademon/src/components/testComponent/testComponent.tsx
  client/trademon/src/store/preferencesSlice.ts
  client/trademon/src/styling/containers.scss
  client/trademon/src/utils/rest.ts
  server/controllers/chatController.js
  server/models/index.js
  server/models/privateChat.model.js
  server/routes.js
Labels: back-end

#185 FE-Feat/Set up mvp routing between trades, myTrades, and DMs
  client/trademon/public/assets/backIcon.png
  client/trademon/src/App.tsx
  client/trademon/src/components/aaPageComponents/addMessage.tsx
  client/trademon/src/components/aaPageComponents/demoAnimation.tsx
  client/trademon/src/components/aaPageComponents/dmChatPage.tsx
  client/trademon/src/components/aaPageComponents/dmPage.tsx
  client/trademon/src/components/aaPageComponents/loginPage.tsx
  client/trademon/src/components/aaPageComponents/tradePage.tsx
  client/trademon/src/components/containerComponents/chatContainer.tsx
  client/trademon/src/components/containerComponents/offerDetailsPokemon.tsx
  client/trademon/src/components/navComponents/navComponent.tsx
  client/trademon/src/components/navComponents/tabsComponent.tsx
  client/trademon/src/components/navComponents/tradeDetailTitleBar.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmSummaryTile.tsx
  client/trademon/src/store/preferencesSlice.ts
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/navs.scss
  client/trademon/src/utils/interfaces.ts
  client/trademon/src/utils/rest.ts
  server/controllers/chatController.js
  server/controllers/pokeTradeController.js
  server/models/index.js
  server/routes.js
Labels: bug, feature, front-end

#186 Fe feat/trade details improvement and messages view
  client/trademon/src/components/aaPageComponents/dmPage.tsx
  client/trademon/src/components/containerComponents/chatContainer.tsx
  client/trademon/src/components/containerComponents/offerDetailsPokemon.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmChatTile.tsx
  client/trademon/src/components/tileComponents/myProfileTileComponents/dmSummaryTile.tsx
  client/trademon/src/store/preferencesSlice.ts
  client/trademon/src/styling/containers.scss
  client/trademon/src/styling/navs.scss
  client/trademon/src/styling/temp_chatPage.scss
  client/trademon/src/styling/tiles.scss
  client/trademon/src/utils/interfaces.ts
  client/trademon/src/utils/rest.ts
  server/controllers/chatController.js
  server/routes.js
Labels: feature, front-end
